In [122]:
import torch

gradients=torch.ones(2,2)

In [123]:
#init x
x=torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn)
print(x.requires_grad)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
True
None


In [124]:
y=x*x;
print(y)
print(y.grad_fn)
print(y.requires_grad)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
True


In [125]:
#backpropogation
# y.backward(gradients) #needs explict parameter
#dy/dx=2*x
# print(x.grad)

In [126]:
z=x.mean()
print(z)
print(z.grad_fn)
print(z.requires_grad)
z.backward(torch.ones(1,1))
print(x.grad)

tensor(1., grad_fn=<MeanBackward0>)
True
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [127]:
# a=y+z
# print(a)
# print(a.grad_fn)
# a.backward(gradients)
# print(x.grad)